// ─── Dummy data for frontend-only rendering (no Supabase) ───

export const DUMMY_USER = {
  id: 'user-001',
  name: 'Jordan Lee',
  email: 'jordan@example.com',
  initials: 'JL',
  plan: 'Pro' as const,
}

export const DUMMY_SCENES = [
  {
    id: 'scene-001',
    reel_id: 'reel-001',
    type: 'hook',
    script_text: "Did you know 90% of creators burn out within 6 months? Here's the system that keeps the top 10% going — and it's not what you think.",
    caption_text: "90% of creators burn out within 6 months.",
    start_sec: 0,
    end_sec: 7,
    sort_order: 0,
    image_url: null,
    audio_url: null,
    image_status: 'ready',
    audio_status: 'ready',
  },
  {
    id: 'scene-002',
    reel_id: 'reel-001',
    type: 'context',
    script_text: "Most creators chase virality instead of building a system. They post every day until they have nothing left to say — no strategy, no reserve, no recharge.",
    caption_text: "Most creators chase virality, not systems.",
    start_sec: 7,
    end_sec: 22,
    sort_order: 1,
    image_url: null,
    audio_url: null,
    image_status: 'ready',
    audio_status: 'ready',
  },
  {
    id: 'scene-003',
    reel_id: 'reel-001',
    type: 'value',
    script_text: "The fix: batch your content in focused 3-hour sessions once a week. Shoot 4–6 reels, schedule them out, then fully disconnect. Consistency without the daily grind.",
    caption_text: "Batch once a week. Disconnect for the rest.",
    start_sec: 22,
    end_sec: 47,
    sort_order: 2,
    image_url: null,
    audio_url: null,
    image_status: 'ready',
    audio_status: 'ready',
  },
  {
    id: 'scene-004',
    reel_id: 'reel-001',
    type: 'cta',
    script_text: "Save this if you're a creator. Drop a 🔥 if you're trying this method this week.",
    caption_text: "Save this. Drop a 🔥 if you're trying this.",
    start_sec: 47,
    end_sec: 55,
    sort_order: 3,
    image_url: null,
    audio_url: null,
    image_status: 'ready',
    audio_status: 'ready',
  },
]

export const DUMMY_REELS = [
  {
    id: 'reel-001',
    title: '5 Creator Burnout Signs',
    template: 'educational',
    status: 'ready',
    duration_sec: 55,
    session_id: 'session-001',
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-20T10:05:00Z',
    scenes: DUMMY_SCENES,
    thumbnail_color: 'from-blue-600 to-blue-900',
  },
  {
    id: 'reel-002',
    title: 'My SaaS Hit $10k MRR',
    template: 'storytelling',
    status: 'ready',
    duration_sec: 60,
    session_id: 'session-002',
    created_at: '2026-03-19T14:00:00Z',
    updated_at: '2026-03-19T14:12:00Z',
    scenes: [],
    thumbnail_color: 'from-purple-600 to-purple-900',
  },
  {
    id: 'reel-003',
    title: 'Stop Using React for This',
    template: 'educational',
    status: 'ready',
    duration_sec: 48,
    session_id: 'session-003',
    created_at: '2026-03-18T09:00:00Z',
    updated_at: '2026-03-18T09:08:00Z',
    scenes: [],
    thumbnail_color: 'from-cyan-600 to-blue-900',
  },
  {
    id: 'reel-004',
    title: 'New Feature Drop 🚀',
    template: 'marketing',
    status: 'generating-assets',
    duration_sec: 30,
    session_id: 'session-004',
    created_at: '2026-03-21T08:00:00Z',
    updated_at: '2026-03-21T08:02:00Z',
    scenes: [],
    thumbnail_color: 'from-yellow-500 to-orange-700',
  },
  {
    id: 'reel-005',
    title: 'Notion Setup for Developers',
    template: 'educational',
    status: 'pending',
    duration_sec: 0,
    session_id: 'session-005',
    created_at: '2026-03-21T09:30:00Z',
    updated_at: '2026-03-21T09:30:00Z',
    scenes: [],
    thumbnail_color: 'from-gray-600 to-gray-900',
  },
  {
    id: 'reel-006',
    title: 'The 5AM Routine That Changed Everything',
    template: 'storytelling',
    status: 'ready',
    duration_sec: 58,
    session_id: 'session-006',
    created_at: '2026-03-17T07:00:00Z',
    updated_at: '2026-03-17T07:10:00Z',
    scenes: [],
    thumbnail_color: 'from-pink-600 to-rose-900',
  },
]

// Public showcase reels for landing page
export const PUBLIC_REELS = [
  {
    id: 'pub-001',
    title: '10 Productivity Hacks in 60 Seconds',
    creator: '@techwithjordan',
    views: '2.4M',
    template: 'educational',
    gradient: 'from-blue-500 via-blue-700 to-indigo-900',
    icon: '⚡',
  },
  {
    id: 'pub-002',
    title: 'How I Built a 6-Figure Newsletter',
    creator: '@sarahbuilds',
    views: '1.1M',
    template: 'storytelling',
    gradient: 'from-purple-500 via-violet-600 to-purple-900',
    icon: '📬',
  },
  {
    id: 'pub-003',
    title: 'The Morning Routine No One Talks About',
    creator: '@mindsetshift',
    views: '890K',
    template: 'entertainment',
    gradient: 'from-orange-400 via-rose-500 to-pink-800',
    icon: '🌅',
  },
  {
    id: 'pub-004',
    title: 'React vs Next.js in 2026 — Honest Take',
    creator: '@devwithalex',
    views: '650K',
    template: 'educational',
    gradient: 'from-cyan-400 via-teal-600 to-cyan-900',
    icon: '💻',
  },
  {
    id: 'pub-005',
    title: 'From 0 to 100K Followers in 90 Days',
    creator: '@growthlab',
    views: '3.2M',
    template: 'storytelling',
    gradient: 'from-green-400 via-emerald-600 to-green-900',
    icon: '📈',
  },
]

export type DummyReel = typeof DUMMY_REELS[0]
export type DummyScene = typeof DUMMY_SCENES[0]
